// <auto-generated />
using System;
using EMS.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EMS.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250714224316_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EMS.Shared.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 22,
                            DateOfBirth = new DateTime(2003, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Human Resources",
                            Name = "Sarah White",
                            PhoneNumber = "07779031884"
                        },
                        new
                        {
                            Id = 2,
                            Age = 53,
                            DateOfBirth = new DateTime(1972, 6, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Engineering",
                            Name = "Michael Smith",
                            PhoneNumber = "07405996016"
                        },
                        new
                        {
                            Id = 3,
                            Age = 42,
                            DateOfBirth = new DateTime(1982, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Operations",
                            Name = "Barbara White",
                            PhoneNumber = "07723366584"
                        },
                        new
                        {
                            Id = 4,
                            Age = 57,
                            DateOfBirth = new DateTime(1967, 10, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Human Resources",
                            Name = "David Brown",
                            PhoneNumber = "07927847324"
                        },
                        new
                        {
                            Id = 5,
                            Age = 31,
                            DateOfBirth = new DateTime(1993, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Operations",
                            Name = "Joseph Jackson",
                            PhoneNumber = "07181099521"
                        },
                        new
                        {
                            Id = 6,
                            Age = 22,
                            DateOfBirth = new DateTime(2003, 5, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "IT",
                            Name = "Susan Harris",
                            PhoneNumber = "07591909908"
                        },
                        new
                        {
                            Id = 7,
                            Age = 21,
                            DateOfBirth = new DateTime(2004, 6, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "IT",
                            Name = "John Brown",
                            PhoneNumber = "07703138056"
                        },
                        new
                        {
                            Id = 8,
                            Age = 40,
                            DateOfBirth = new DateTime(1984, 11, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "IT",
                            Name = "John Harris",
                            PhoneNumber = "07553537983"
                        },
                        new
                        {
                            Id = 9,
                            Age = 48,
                            DateOfBirth = new DateTime(1977, 3, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Engineering",
                            Name = "James Martin",
                            PhoneNumber = "07181776514"
                        },
                        new
                        {
                            Id = 10,
                            Age = 25,
                            DateOfBirth = new DateTime(2000, 1, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Engineering",
                            Name = "James Thomas",
                            PhoneNumber = "07810253031"
                        },
                        new
                        {
                            Id = 11,
                            Age = 53,
                            DateOfBirth = new DateTime(1971, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Operations",
                            Name = "Elizabeth Thomas",
                            PhoneNumber = "07511913220"
                        },
                        new
                        {
                            Id = 12,
                            Age = 38,
                            DateOfBirth = new DateTime(1986, 12, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Finance",
                            Name = "Charles Johnson",
                            PhoneNumber = "07127276230"
                        },
                        new
                        {
                            Id = 13,
                            Age = 34,
                            DateOfBirth = new DateTime(1991, 4, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Finance",
                            Name = "Elizabeth Thomas",
                            PhoneNumber = "07845105766"
                        },
                        new
                        {
                            Id = 14,
                            Age = 27,
                            DateOfBirth = new DateTime(1997, 10, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Finance",
                            Name = "Barbara Harris",
                            PhoneNumber = "07597040756"
                        },
                        new
                        {
                            Id = 15,
                            Age = 42,
                            DateOfBirth = new DateTime(1982, 10, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "IT",
                            Name = "Elizabeth Smith",
                            PhoneNumber = "07705949211"
                        },
                        new
                        {
                            Id = 16,
                            Age = 43,
                            DateOfBirth = new DateTime(1982, 7, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Engineering",
                            Name = "James Thomas",
                            PhoneNumber = "07750723106"
                        },
                        new
                        {
                            Id = 17,
                            Age = 31,
                            DateOfBirth = new DateTime(1994, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Marketing",
                            Name = "David Jackson",
                            PhoneNumber = "07609234811"
                        },
                        new
                        {
                            Id = 18,
                            Age = 53,
                            DateOfBirth = new DateTime(1971, 10, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Human Resources",
                            Name = "Michael Taylor",
                            PhoneNumber = "07854362849"
                        },
                        new
                        {
                            Id = 19,
                            Age = 36,
                            DateOfBirth = new DateTime(1988, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Human Resources",
                            Name = "Jessica Smith",
                            PhoneNumber = "07759790344"
                        },
                        new
                        {
                            Id = 20,
                            Age = 37,
                            DateOfBirth = new DateTime(1987, 11, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Finance",
                            Name = "Jessica Jackson",
                            PhoneNumber = "07148887791"
                        },
                        new
                        {
                            Id = 21,
                            Age = 22,
                            DateOfBirth = new DateTime(2003, 1, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Operations",
                            Name = "William Harris",
                            PhoneNumber = "07237076891"
                        },
                        new
                        {
                            Id = 22,
                            Age = 24,
                            DateOfBirth = new DateTime(2001, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Sales",
                            Name = "Thomas Martin",
                            PhoneNumber = "07756386023"
                        },
                        new
                        {
                            Id = 23,
                            Age = 36,
                            DateOfBirth = new DateTime(1988, 11, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "IT",
                            Name = "James Jackson",
                            PhoneNumber = "07803841951"
                        },
                        new
                        {
                            Id = 24,
                            Age = 30,
                            DateOfBirth = new DateTime(1994, 11, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Marketing",
                            Name = "David Harris",
                            PhoneNumber = "07473674841"
                        },
                        new
                        {
                            Id = 25,
                            Age = 25,
                            DateOfBirth = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Sales",
                            Name = "Charles Harris",
                            PhoneNumber = "07669455070"
                        },
                        new
                        {
                            Id = 26,
                            Age = 56,
                            DateOfBirth = new DateTime(1969, 6, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Human Resources",
                            Name = "James White",
                            PhoneNumber = "07919480245"
                        },
                        new
                        {
                            Id = 27,
                            Age = 41,
                            DateOfBirth = new DateTime(1984, 5, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Engineering",
                            Name = "Patricia White",
                            PhoneNumber = "07762186566"
                        },
                        new
                        {
                            Id = 28,
                            Age = 50,
                            DateOfBirth = new DateTime(1975, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Operations",
                            Name = "Linda Smith",
                            PhoneNumber = "07617023123"
                        },
                        new
                        {
                            Id = 29,
                            Age = 55,
                            DateOfBirth = new DateTime(1969, 10, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Finance",
                            Name = "Karen Martin",
                            PhoneNumber = "07926549427"
                        },
                        new
                        {
                            Id = 30,
                            Age = 21,
                            DateOfBirth = new DateTime(2003, 12, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Finance",
                            Name = "William Johnson",
                            PhoneNumber = "07423900169"
                        },
                        new
                        {
                            Id = 31,
                            Age = 53,
                            DateOfBirth = new DateTime(1971, 12, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Engineering",
                            Name = "Richard White",
                            PhoneNumber = "07843478129"
                        },
                        new
                        {
                            Id = 32,
                            Age = 45,
                            DateOfBirth = new DateTime(1980, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Engineering",
                            Name = "Jennifer Taylor",
                            PhoneNumber = "07965796452"
                        },
                        new
                        {
                            Id = 33,
                            Age = 50,
                            DateOfBirth = new DateTime(1974, 12, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Sales",
                            Name = "Michael Taylor",
                            PhoneNumber = "07696515560"
                        },
                        new
                        {
                            Id = 34,
                            Age = 56,
                            DateOfBirth = new DateTime(1968, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Engineering",
                            Name = "Susan Taylor",
                            PhoneNumber = "07640266298"
                        },
                        new
                        {
                            Id = 35,
                            Age = 59,
                            DateOfBirth = new DateTime(1965, 9, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Finance",
                            Name = "Richard Taylor",
                            PhoneNumber = "07805345253"
                        },
                        new
                        {
                            Id = 36,
                            Age = 53,
                            DateOfBirth = new DateTime(1972, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Operations",
                            Name = "Thomas Smith",
                            PhoneNumber = "07456129635"
                        },
                        new
                        {
                            Id = 37,
                            Age = 24,
                            DateOfBirth = new DateTime(2000, 12, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Finance",
                            Name = "Jessica White",
                            PhoneNumber = "07599619258"
                        },
                        new
                        {
                            Id = 38,
                            Age = 48,
                            DateOfBirth = new DateTime(1977, 6, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Finance",
                            Name = "William Harris",
                            PhoneNumber = "07806874986"
                        },
                        new
                        {
                            Id = 39,
                            Age = 39,
                            DateOfBirth = new DateTime(1986, 6, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "IT",
                            Name = "Karen Thomas",
                            PhoneNumber = "07330112191"
                        },
                        new
                        {
                            Id = 40,
                            Age = 28,
                            DateOfBirth = new DateTime(1996, 10, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Engineering",
                            Name = "Thomas Martin",
                            PhoneNumber = "07297937662"
                        },
                        new
                        {
                            Id = 41,
                            Age = 48,
                            DateOfBirth = new DateTime(1977, 7, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Marketing",
                            Name = "Sarah Johnson",
                            PhoneNumber = "07878666073"
                        },
                        new
                        {
                            Id = 42,
                            Age = 23,
                            DateOfBirth = new DateTime(2002, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Human Resources",
                            Name = "Robert Martin",
                            PhoneNumber = "07734912769"
                        },
                        new
                        {
                            Id = 43,
                            Age = 35,
                            DateOfBirth = new DateTime(1990, 4, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Sales",
                            Name = "Barbara Harris",
                            PhoneNumber = "07244477956"
                        },
                        new
                        {
                            Id = 44,
                            Age = 33,
                            DateOfBirth = new DateTime(1992, 4, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Finance",
                            Name = "Joseph Anderson",
                            PhoneNumber = "07603477481"
                        },
                        new
                        {
                            Id = 45,
                            Age = 47,
                            DateOfBirth = new DateTime(1977, 7, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Operations",
                            Name = "Susan Thomas",
                            PhoneNumber = "07853322251"
                        },
                        new
                        {
                            Id = 46,
                            Age = 48,
                            DateOfBirth = new DateTime(1976, 10, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "IT",
                            Name = "David Johnson",
                            PhoneNumber = "07629191335"
                        },
                        new
                        {
                            Id = 47,
                            Age = 57,
                            DateOfBirth = new DateTime(1967, 12, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Sales",
                            Name = "Patricia Smith",
                            PhoneNumber = "07674021358"
                        },
                        new
                        {
                            Id = 48,
                            Age = 52,
                            DateOfBirth = new DateTime(1973, 4, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Operations",
                            Name = "Sarah White",
                            PhoneNumber = "07907677659"
                        },
                        new
                        {
                            Id = 49,
                            Age = 53,
                            DateOfBirth = new DateTime(1971, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Engineering",
                            Name = "Robert Harris",
                            PhoneNumber = "07487148699"
                        },
                        new
                        {
                            Id = 50,
                            Age = 54,
                            DateOfBirth = new DateTime(1970, 8, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "IT",
                            Name = "Karen Smith",
                            PhoneNumber = "07561798091"
                        },
                        new
                        {
                            Id = 51,
                            Age = 52,
                            DateOfBirth = new DateTime(1972, 8, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "IT",
                            Name = "Michael Taylor",
                            PhoneNumber = "07353270886"
                        },
                        new
                        {
                            Id = 52,
                            Age = 54,
                            DateOfBirth = new DateTime(1970, 8, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Human Resources",
                            Name = "Charles Harris",
                            PhoneNumber = "07436945931"
                        },
                        new
                        {
                            Id = 53,
                            Age = 48,
                            DateOfBirth = new DateTime(1976, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "IT",
                            Name = "James Taylor",
                            PhoneNumber = "07377877117"
                        },
                        new
                        {
                            Id = 54,
                            Age = 27,
                            DateOfBirth = new DateTime(1998, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Operations",
                            Name = "James White",
                            PhoneNumber = "07572950326"
                        },
                        new
                        {
                            Id = 55,
                            Age = 58,
                            DateOfBirth = new DateTime(1967, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "IT",
                            Name = "Sarah Harris",
                            PhoneNumber = "07985873735"
                        },
                        new
                        {
                            Id = 56,
                            Age = 25,
                            DateOfBirth = new DateTime(2000, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Operations",
                            Name = "Sarah Taylor",
                            PhoneNumber = "07301091971"
                        },
                        new
                        {
                            Id = 57,
                            Age = 29,
                            DateOfBirth = new DateTime(1995, 11, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Sales",
                            Name = "Barbara Thomas",
                            PhoneNumber = "07136770631"
                        },
                        new
                        {
                            Id = 58,
                            Age = 48,
                            DateOfBirth = new DateTime(1976, 10, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Marketing",
                            Name = "Jennifer Martin",
                            PhoneNumber = "07822441011"
                        },
                        new
                        {
                            Id = 59,
                            Age = 37,
                            DateOfBirth = new DateTime(1988, 7, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Engineering",
                            Name = "Jennifer Anderson",
                            PhoneNumber = "07284746652"
                        },
                        new
                        {
                            Id = 60,
                            Age = 55,
                            DateOfBirth = new DateTime(1969, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Finance",
                            Name = "Joseph Harris",
                            PhoneNumber = "07278400033"
                        },
                        new
                        {
                            Id = 61,
                            Age = 56,
                            DateOfBirth = new DateTime(1969, 3, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Finance",
                            Name = "Michael Martin",
                            PhoneNumber = "07324803945"
                        },
                        new
                        {
                            Id = 62,
                            Age = 42,
                            DateOfBirth = new DateTime(1982, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Sales",
                            Name = "Sarah Jackson",
                            PhoneNumber = "07338647847"
                        },
                        new
                        {
                            Id = 63,
                            Age = 52,
                            DateOfBirth = new DateTime(1973, 7, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Human Resources",
                            Name = "Robert Harris",
                            PhoneNumber = "07760642182"
                        },
                        new
                        {
                            Id = 64,
                            Age = 47,
                            DateOfBirth = new DateTime(1977, 10, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Human Resources",
                            Name = "James Brown",
                            PhoneNumber = "07141991091"
                        },
                        new
                        {
                            Id = 65,
                            Age = 42,
                            DateOfBirth = new DateTime(1983, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Marketing",
                            Name = "Jessica Martin",
                            PhoneNumber = "07754539848"
                        },
                        new
                        {
                            Id = 66,
                            Age = 23,
                            DateOfBirth = new DateTime(2001, 12, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Sales",
                            Name = "Mary White",
                            PhoneNumber = "07953313015"
                        },
                        new
                        {
                            Id = 67,
                            Age = 32,
                            DateOfBirth = new DateTime(1992, 8, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Engineering",
                            Name = "Sarah Smith",
                            PhoneNumber = "07605948455"
                        },
                        new
                        {
                            Id = 68,
                            Age = 48,
                            DateOfBirth = new DateTime(1977, 2, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Sales",
                            Name = "Michael Brown",
                            PhoneNumber = "07509839705"
                        },
                        new
                        {
                            Id = 69,
                            Age = 29,
                            DateOfBirth = new DateTime(1996, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Marketing",
                            Name = "Barbara Thomas",
                            PhoneNumber = "07844609971"
                        },
                        new
                        {
                            Id = 70,
                            Age = 24,
                            DateOfBirth = new DateTime(2000, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "IT",
                            Name = "Patricia Brown",
                            PhoneNumber = "07895633187"
                        },
                        new
                        {
                            Id = 71,
                            Age = 42,
                            DateOfBirth = new DateTime(1982, 11, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Human Resources",
                            Name = "William Jackson",
                            PhoneNumber = "07661574151"
                        },
                        new
                        {
                            Id = 72,
                            Age = 39,
                            DateOfBirth = new DateTime(1986, 4, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Sales",
                            Name = "Linda Anderson",
                            PhoneNumber = "07247075237"
                        },
                        new
                        {
                            Id = 73,
                            Age = 49,
                            DateOfBirth = new DateTime(1975, 10, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Finance",
                            Name = "Mary Brown",
                            PhoneNumber = "07937748893"
                        },
                        new
                        {
                            Id = 74,
                            Age = 39,
                            DateOfBirth = new DateTime(1986, 5, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Sales",
                            Name = "Barbara White",
                            PhoneNumber = "07623162570"
                        },
                        new
                        {
                            Id = 75,
                            Age = 26,
                            DateOfBirth = new DateTime(1999, 1, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Operations",
                            Name = "Patricia Jackson",
                            PhoneNumber = "07595791592"
                        },
                        new
                        {
                            Id = 76,
                            Age = 44,
                            DateOfBirth = new DateTime(1980, 8, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Finance",
                            Name = "Sarah Thomas",
                            PhoneNumber = "07130387126"
                        },
                        new
                        {
                            Id = 77,
                            Age = 42,
                            DateOfBirth = new DateTime(1983, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Marketing",
                            Name = "Barbara Taylor",
                            PhoneNumber = "07593184245"
                        },
                        new
                        {
                            Id = 78,
                            Age = 22,
                            DateOfBirth = new DateTime(2002, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Finance",
                            Name = "Thomas Jackson",
                            PhoneNumber = "07514553698"
                        },
                        new
                        {
                            Id = 79,
                            Age = 39,
                            DateOfBirth = new DateTime(1985, 8, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Marketing",
                            Name = "Susan Harris",
                            PhoneNumber = "07560658854"
                        },
                        new
                        {
                            Id = 80,
                            Age = 52,
                            DateOfBirth = new DateTime(1972, 11, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "IT",
                            Name = "Charles White",
                            PhoneNumber = "07554763589"
                        },
                        new
                        {
                            Id = 81,
                            Age = 51,
                            DateOfBirth = new DateTime(1973, 8, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Operations",
                            Name = "Patricia Brown",
                            PhoneNumber = "07541817257"
                        },
                        new
                        {
                            Id = 82,
                            Age = 26,
                            DateOfBirth = new DateTime(1999, 5, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Marketing",
                            Name = "Sarah Harris",
                            PhoneNumber = "07483579404"
                        },
                        new
                        {
                            Id = 83,
                            Age = 60,
                            DateOfBirth = new DateTime(1965, 5, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Sales",
                            Name = "Mary Smith",
                            PhoneNumber = "07707843674"
                        },
                        new
                        {
                            Id = 84,
                            Age = 51,
                            DateOfBirth = new DateTime(1974, 5, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Finance",
                            Name = "Sarah Jackson",
                            PhoneNumber = "07544654541"
                        },
                        new
                        {
                            Id = 85,
                            Age = 54,
                            DateOfBirth = new DateTime(1970, 7, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "IT",
                            Name = "Mary Jackson",
                            PhoneNumber = "07722371088"
                        },
                        new
                        {
                            Id = 86,
                            Age = 37,
                            DateOfBirth = new DateTime(1988, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Marketing",
                            Name = "Michael Jackson",
                            PhoneNumber = "07199744962"
                        },
                        new
                        {
                            Id = 87,
                            Age = 32,
                            DateOfBirth = new DateTime(1992, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "IT",
                            Name = "Charles Jackson",
                            PhoneNumber = "07274577595"
                        },
                        new
                        {
                            Id = 88,
                            Age = 32,
                            DateOfBirth = new DateTime(1993, 5, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Marketing",
                            Name = "Joseph Taylor",
                            PhoneNumber = "07166522141"
                        },
                        new
                        {
                            Id = 89,
                            Age = 43,
                            DateOfBirth = new DateTime(1981, 7, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Human Resources",
                            Name = "Mary Taylor",
                            PhoneNumber = "07935981690"
                        },
                        new
                        {
                            Id = 90,
                            Age = 46,
                            DateOfBirth = new DateTime(1978, 10, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Engineering",
                            Name = "Thomas Smith",
                            PhoneNumber = "07950667766"
                        },
                        new
                        {
                            Id = 91,
                            Age = 51,
                            DateOfBirth = new DateTime(1974, 7, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Sales",
                            Name = "David Harris",
                            PhoneNumber = "07554535801"
                        },
                        new
                        {
                            Id = 92,
                            Age = 59,
                            DateOfBirth = new DateTime(1966, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Engineering",
                            Name = "William Jackson",
                            PhoneNumber = "07353296613"
                        },
                        new
                        {
                            Id = 93,
                            Age = 51,
                            DateOfBirth = new DateTime(1973, 12, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Human Resources",
                            Name = "Patricia Anderson",
                            PhoneNumber = "07248652870"
                        },
                        new
                        {
                            Id = 94,
                            Age = 35,
                            DateOfBirth = new DateTime(1990, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Human Resources",
                            Name = "Jessica Martin",
                            PhoneNumber = "07575233975"
                        },
                        new
                        {
                            Id = 95,
                            Age = 28,
                            DateOfBirth = new DateTime(1997, 4, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Sales",
                            Name = "Robert Jackson",
                            PhoneNumber = "07937935843"
                        },
                        new
                        {
                            Id = 96,
                            Age = 23,
                            DateOfBirth = new DateTime(2002, 2, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Finance",
                            Name = "Linda White",
                            PhoneNumber = "07971959917"
                        },
                        new
                        {
                            Id = 97,
                            Age = 41,
                            DateOfBirth = new DateTime(1984, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Finance",
                            Name = "Barbara Taylor",
                            PhoneNumber = "07741465574"
                        },
                        new
                        {
                            Id = 98,
                            Age = 34,
                            DateOfBirth = new DateTime(1990, 7, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Sales",
                            Name = "Elizabeth Harris",
                            PhoneNumber = "07492854354"
                        },
                        new
                        {
                            Id = 99,
                            Age = 32,
                            DateOfBirth = new DateTime(1992, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Operations",
                            Name = "Elizabeth Thomas",
                            PhoneNumber = "07124244947"
                        },
                        new
                        {
                            Id = 100,
                            Age = 29,
                            DateOfBirth = new DateTime(1995, 12, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Finance",
                            Name = "David Smith",
                            PhoneNumber = "07949159961"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
